#!/usr/bin/python2

import os
from os.path import expanduser
import ConfigParser
import time
import sys
import getpass
import numpy as np
import subprocess as sp

home = expanduser("~")
fpath = home + '/clive.cfg'
cfg = ConfigParser.SafeConfigParser()
#from clive.core.conf import Configure

class Configure():
    def __init__(self):
        self.load()

    def __getitem__(self, key):
        return self.__dict__[key]

    def __setitem__(self, key, value):
        self.__dict__[key] = value

    def __repr__(self):
        return str(self.__dict__)

    def load(self):
        cfg.read(fpath)
        for section in cfg.sections():
            for option in cfg.options(section):
                key = (section, option)
                value = cfg.get(section, option)
                self.__dict__[key] = value
    
    def update(self):
        for key, value in self.__dict__.items():
            section, option = key
            try:
                cfg.set(section, option, value)
            except ConfigParser.NoSectionError:
                cfg.add_section(section)
                cfg.set(section, option, value)
            except Exception as e:
                print e.message
                quit()

            f = open(fpath,'w')
            cfg.write(f)
        f.close()
    
    
    def check(self):
        for key, value in self.__dict__.items():
            if value == "":
                print "Section [%s] Option [%s]: no value" % key
                quit()


    def set_default(self):
        sets = [
        (('admin','name'),'admin'),
        (('admin','email'),'admin@host.com'),

        (('db','host'),'localhost'),
        (('db','db'),'clive1'),
        (('db','user'),'clive'),
        (('db','pass'),'colonylive'),
        (('db','port'),'3306'),

        (('folder','img_tmp'),'%s/img_tmp/' % home),
        (('folder','img_scan'),'%s/img_scan/' % home),
        (('folder','img_store'),'%s/img/' % home),

        (('scan','scanner_ids'),''),
        (('scan','min_cycle'),'30'),
        (('scan','days_scan_keep'),'30'),
        
        (('colony','r_center_mass'),'8'),

        (('growth','od_limit'),'1'),
        (('growth','point_number_use'),'100'),
        (('growth','frac_limit_ip'),'0.8'),
        (('growth','min_fixed_time_point'),'1200'),

        (('vuescan','pos_input_tab'),''),
        (('vuescan','pos_source'),''),
        (('vuescan','pos_mode'),''),
        (('vuescan','pos_abort'),''),
        (('vuescan','sec_scan_wait'),'240'),
        
        (('setup','step'),'0')
        ]
        
        for key, value in sets:
            self.__dict__[key] = value
        self.update()


cfg = Configure()


def main():
    #set_package()
    #set_config()
    set_database()
    set_vuescan()
    set_layout()


# Install packages
#==================================================

def set_package():
    os.system('clear')
    print "Install packages"
    print "========================="
    print 
    print "updating package info..."
    sp.call('sudo apt-get -qq update',shell=True)
    items = [
        'r-base',
        'mysql-server',
        'ntpdate',
        'xautomation',
        'wmctrl',
        'python-mysqldb',
        'python-numpy',
        'python-scipy',
        'python-opencv',
        'python-matplotlib',
        #'python-sqlalchemy',
        'python-rpy2',
        'python-webpy'
        ]
    for item in items:
        print "install %s" % item
        cmd = 'sudo apt-get -qq -y install %s' % item
        sp.call(cmd,shell=True)

    print "\nDONE"
    raw_input("Press Enter...")



# config file
#==================================================

try:
    cfg.load()
    step = int(cfg[('setup','step')])
except:
    cfg.set_default()
    cfg.update()


def set_value(msg, key):
    try: 
        default = cfg[key]
    except:
        default = ''

    while True:
        ans = raw_input("%s [%s]: " % (msg, default))
        if ans == "":
            if default != '':
                value = default
                break
        else:
            value = ans
            break
    cfg[key] = value
    cfg.update()


def set_config():
    os.system('clear')
    print "Configure setting"
    print "========================="
    print "Item [Current value]: "
    print 
    print "Adiminstrator"
    set_value('- Name', ('admin','name'))
    set_value('- email', ('admin','email'))

    print "\nConnected scanner IDs -- e.g.) 1,2,3"
    set_value('- IDs', ('scan','scanner_ids'))

    print "\nDONE"
    raw_input("Press Enter...")



# Database setting
#==================================================


def set_database():
    from clive.db.database import DB
    from clive.db.schema import make_all_tables
    from clive.db.handler import ScannerHandler
    scanner_handler = ScannerHandler()

    os.system('clear')
    print "Database Setting"
    print "========================="
    print 
    db = DB()
    try:
        db.session.execute("show tables")
    except:
        try:
            create_user_and_db()
        except:
            print "Cannot connect to MySQL database"
        db.session.execute("show tables")
    
    make_all_tables()
    
    # create sid
    sids = map(int, cfg[('scan','scanner_ids')].split(","))
    for sid in sids:
        try:
            scanner_handler.load(sid)
        except:
            scanner_handler.create(sid)
    
    print "\nDONE"
    raw_input("Press Enter...")


def create_user_and_db():
    host = cfg[('db','host')]
    port = cfg[('db','port')]
    dbname = cfg[('db','db')]
    user = cfg[('db','user')]
    passwd = cfg[('db','pass')]
    cmd = "mysql -h %s -P %s -u root -p mysql -e \"GRANT ALL ON *.* TO %s@'localhost' IDENTIFIED BY '%s'; FLUSH PRIVILEGES;\"" % (host, port, user, passwd)
    print "Enter password of MySQL root (not system root!)"
    sp.call(cmd,shell=True)
    
    cmd = "mysql -h %s -P %s -u %s -p%s -e \"CREATE DATABASE %s\"" % (host, port, user, passwd, dbname)
    sp.call(cmd,shell=True)



# VueScan setting
#==================================================

def set_vuescan():
    from clive.setup.auto_vuescan import gui_setup
    from clive.setup.conf_vuescan import make_conf

    os.system('clear')
    print "VueScan Setting"
    print "========================="
    print 
    
    if cfg[('vuescan','pos_input_tab')] != "":
        while True:
            ans = raw_input("Re-setup? yes or no:")
            if ans in ["yes", 'y']:
                break
            if ans in ["no", 'n']:
                return

    gui_setup()
    make_conf()
    
    print "\nDONE"
    raw_input("Press Enter...")



# Clip layout
#==================================================

def set_layout():
    from clive.setup.clip_layout import layout_setup
    from clive.scan.gui_scan import gui_scan
    from clive.scan.prep import prep_gui

    os.system('clear')
    print "Scan layout Setting"
    print "========================="
    print
    
    print "Which scanner you will use for setup?"
    sids = cfg[('scan','scanner_ids')]
    print "Available scanner IDs: %s" % sids
    while True:
        ans = raw_input("scanner ID:")
        if ans in sids:
            sid = int(ans)
            break
    
    print "Set all test plates on the scanner ID %d, then press enter" % sid
    raw_input("Press enter:")
    
    print "Start scanning... Don't touch mouse and keyboard during the scanning"
    raw_input("Press enter:")
    
    prep_gui()

    gui_scan(sid, "layout_set.tif")
    
    print "starting Inkscape..."
    print "Draw red box on the test plates, then save as png file"
    raw_input("Press enter:")

    cmd = "inkscape layout_set.tif"
    sp.call(cmd,shell=True)
    
    layout_setup("layout_set.png")

    print "\nDONE"
    raw_input("Press Enter...")


if __name__ == "__main__":
    main()

