#!/usr/bin/env python2

"""
 Start web service to manage colony-live system

"""

import clive.web.code

print clive.web.code.__file__
from clive.web.code import app

def start_web():
    app.run()


if __name__ == "__main__":
    start_web()
