#!/usr/bin/python

import sys
import getpass
import numpy as np

from clive-analysis import peform_analysis


jobs = []
jobs += [Process(target=perform_analysis, )]

for j in jobs:
    j.start()
for j in jobs:
    j.join()

print "stop"
